// <auto-generated />
namespace WebShop.BusinessLogic.Migrations.ProductContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddImageString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddImageString));
        
        string IMigrationMetadata.Id
        {
            get { return "202504011913010_AddImageString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
